# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fd98f0cb583de6a6a2575b47e0a609418e442b327b665ba18cadd0706e3eeb3723dbe0f56187590ac106e486dbd87cbdbcbdace446483d384dfcc1ea20100332

test:
  secret_key_base: f7f1489cc8df9d0d10e86ce579ae9e0bb6bc44b0047cffae953b13c67cca08609d360ca6935549685bf652b393a939e270251acd8bf28258239d3618a231ed74

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
